(define 
    (problem tsp)
    (:domain tsp)
    (:objects Trento Trieste Verona Bologna Bari Roma Milano)
    (:init 
        ;;double connection in order to make the graph undirected
        (connected Trento Trieste)
        (connected Trieste Trento)
        (connected Trento Verona)
        (connected Verona Trento)
        (connected Trieste Verona)
        (connected Verona Trieste)
        (connected Trieste Bologna)
        (connected Bologna Trieste)
        (connected Bologna Verona)
        (connected Verona Bologna)
        (connected Bologna Bari)
        (connected Bari Bologna)
        (connected Bari Roma)
        (connected Roma Bari)
        (connected Roma Milano)
        (connected Milano Roma)
        (connected Roma Verona)
        (connected Verona Roma)
        (connected Milano Verona)
        (connected Verona Milano)
        (position Trento)
    )
    (:goal (and
        (position Trento)
        (visited Trento)
        (visited Verona)
        (visited Trieste)
        (visited Bologna)
        (visited Milano)
        (visited Roma)
        (visited Bari)
    ))
)